---
name: Filesys-Virtual-Async-inMemory
version: 0.01
author:
  - 'Apocalypse <APOCAL@cpan.org>'
abstract: In-Memory filesystem using the Filesys::Virtual::Async API
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Errno: 0
  Fcntl: 0
  Filesys::Virtual::Async: 0
  IO::Scalar: 0
build_requires:
  Test::More: 0.86
dynamic_config: 0
provides:
  Filesys::Virtual::Async::inMemory:
    file: lib/Filesys/Virtual/Async/inMemory.pm
    version: 0.01
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
